name: Documentation
on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.13
      - name: Setup Poetry package manager
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4
      - name: Install Pandoc
        run: sudo apt-get -qq pandoc
      - name: Install Python dependencies
        run: poetry install
      - name: Build Sphinx docs
        run: poetry run ./docs/scripts/build.sh
      - name: Deploy Sphinx docs
        run: poetry run ./docs/scripts/deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
